# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Generate & publish

on:
  schedule:
    - cron:  '0 */3 * * *'

  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: "7.17.0"
          run_install: true
      - run: sh generate.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish || true
        working-directory: config/effect__io/dist
      - run: npm publish || true
        working-directory: config/effect__stm/dist
      - run: npm publish || true
        working-directory: config/effect__stream/dist
      - run: npm publish || true
        working-directory: config/fp-ts__data/dist
      - run: npm publish || true
        working-directory: config/fp-ts__optic/dist
      - run: npm publish || true
        working-directory: config/fp-ts__schema/dist
