# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Generate & publish

on:
  schedule:
    - cron:  '0 */3 * * *'

  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: "7.17.0"
          run_install: true
      - run: sh setup-npm.sh
        env:
          NPM_TOKEN: ${{secrets.npm_token}}
      - run: sh generate.sh
